### ISSUE TITLE
Spec failing without local ete server - OutputElementsController#index

### ISSUE THREAD

**Issue by ploh** [quintel/etmodel#2290]
```
1) OutputElementsController#index should render the page correctly
     Failure/Error: get :index
     VCR::Errors::UnhandledHTTPRequestError:
           
       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         GET https://beta-engine.energytransitionmodel.com/api/v3/areas.json
       
       There is currently no cassette in use. There are a few ways
       you can configure VCR to handle this request:
       
         * If you're surprised VCR is raising this error
           and want insight about how VCR attempted to handle the request,
           you can use the debug_logger configuration option to log more details [1].
         * If you want VCR to record this request and play it back during future test
           runs, you should wrap your test (or this portion of your test) in a
           `VCR.use_cassette` block [2].
         * If you only want VCR to handle requests made while a cassette is in use,
           configure `allow_http_connections_when_no_cassette = true`. VCR will
           ignore this request since it is made when there is no cassette [3].
         * If you want VCR to ignore this request (and others like it), you can
           set an `ignore_request` callback [4].
       
       [1] https://www.relishapp.com/vcr/vcr/v/2-4-0/docs/configuration/debug-logging
       [2] https://www.relishapp.com/vcr/vcr/v/2-4-0/docs/getting-started
       [3] https://www.relishapp.com/vcr/vcr/v/2-4-0/docs/configuration/allow-http-connections-when-no-cassette
       [4] https://www.relishapp.com/vcr/vcr/v/2-4-0/docs/configuration/ignore-request
       ================================================================================
     # ./app/models/api/area.rb:38:in `block in find_by_country_memoized'
     # ./app/models/api/area.rb:37:in `find_by_country_memoized'
     # ./app/models/setting.rb:128:in `area'
     # ./app/models/area_dependent.rb:5:in `area_dependent'
     # ./app/models/output_element.rb:105:in `whitelisted'
     # ./app/models/output_element.rb:95:in `select_by_group'
     # ./app/controllers/output_elements_controller.rb:24:in `index'
     # ./spec/controllers/output_elements_controller_spec.rb:8:in `block (3 levels) in <top (required)>'
```

1. Only happens if I do not have a local etengine server running.

2. Interestingly, it even happens if the etmodel api_url is set to beta-engine.

**Comment by antw** [comment]
I can't reproduce this, either by running the whole test suite or just that one test. The simplest solution would be to change:

```ruby
describe OutputElementsController do
```

... to ...

```ruby
describe OutputElementsController, vcr: true do
```

You may have to [change this option](https://github.com/quintel/etmodel/blob/83f153f34bca1fa40ac2c3e8a10483b3df60a3b6/spec/spec_helper.rb#L38-L42) in order for the VCR library to record the request.

However I'm confused that the test would be trying to make a request to `areas.json` when you run it, but not when I do; that makes no sense to me. 😖 [I recently disabled caching in the test env](https://github.com/quintel/etmodel/commit/2b1397f2546a881b37a7093fbf029f6eab9ccb0f), so it shouldn't be that.
